#!/usr/bin/env bash
# Increment 1 — validate sshpiper routing on this host BEFORE refactoring devenv/templates.
# Generates the gateway's upstream keypair and writes gateway/.env for compose to consume.
# Run:  ./setup.sh  then  docker compose up -d
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
mkdir -p keys

# base64 as a single line (macOS base64 differs from GNU; strip any newlines)
b64() { base64 < "$1" | tr -d '\n'; }

# 1. Gateway UPSTREAM keypair (sshpiper -> container). One pair, trusted by every container.
if [ ! -f keys/upstream ]; then
  ssh-keygen -t ed25519 -f keys/upstream -N "" -C sshpiper-upstream >/dev/null
  echo "generated keys/upstream{,.pub}"
fi

# 2. Your DOWNSTREAM pubkey (you -> sshpiper)
USER_PUB="${HOME}/.ssh/id_ed25519.pub"
[ -f "$USER_PUB" ] || { echo "error: no $USER_PUB — run ssh-keygen"; exit 1; }

cat > .env <<EOF
# generated by setup.sh — DO NOT COMMIT
GATEWAY_PUBKEY=$(cat keys/upstream.pub)
GATEWAY_PRIVKEY_B64=$(b64 keys/upstream)
USER_PUBKEY_B64=$(b64 "$USER_PUB")
EOF
echo "wrote gateway/.env"
echo "next: docker compose up -d   then   ssh -o StrictHostKeyChecking=no test@localhost -p 2200"
